name: Abiword Appimage
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "0 21 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
    - uses: actions/checkout@v3

    - name: build
      if: always()
      run: |
        pacman -Syu --noconfirm && pacman -S --noconfirm desktop-file-utils wget
        wget https://raw.githubusercontent.com/ivan-hc/Abiword-appimage/main/abiword-junest.sh
        chmod a+x ./abiword-junest.sh
        ./abiword-junest.sh
        mkdir dist
        mv *AppImage dist/

    - name: Upload artifact
      uses: actions/upload-artifact@v4.4.0
      with:
        name: Abiword-x86_64.AppImage
        path: 'dist'
        
  release:
      needs: [build]
      permissions: write-all
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v4.1.8
          with:
            name: Abiword-x86_64.AppImage

        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: Continuous build
            automatic_release_tag: continuous
            prerelease: false
            draft: false
            files: |
              *.AppImage
            repo_token: ${{ secrets.GITHUB_TOKEN }}
